.catalog:
  name: Jupyter - Tensorflow 
  version: 0.1
  description: Jupyter + Tensorflow
  uuid: Jupyter-Tensorflow-0
  minimum_rancher_version: v0.46.0
  questions: 
    - variable: PORT
      default: 8888
      label: Public port
      required: true
    - variable: TOKEN
      label: Token
      required: true
      type: password
