# notemplating
.catalog:
  name: "DNSimple DNS"
  version: "v0.7.11"
  description: "Rancher External DNS service powered by DNSimple"
  minimum_rancher_version: v1.6.0
  questions:
    - variable: "DNSIMPLE_ACCOUNT_TOKEN"
      label: "DNSimple Account Access Token"
      description: "OAuth account access token for your DNSimple account."
      type: "string"
      required: true
    - variable: "ROOT_DOMAIN"
      label: "Root Domain"
      description: "The domain name managed by DNSimple."
      type: "string"
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds"
      type: "int"
      default: 60
      required: false
    - variable: "NAME_TEMPLATE"
      label: "DNS Name Template"
      description: |
        Name template used to construct the subdomain part (left of the root domain name) of the DNS record names.
        Supported placeholders: %{{service_name}}, %{{stack_name}}, %{{environment_name}}.
        By default DNS entries will be named '<service>.<stack>.<environment>.<domain>'.
      type: "string"
      default: "%{{service_name}}.%{{stack_name}}.%{{environment_name}}"
      required: false
    - variable: "HEALTH_CHECK"
      label: "Health Check Interval"
      description: |
        The health check interval for this service, in milliseconds.
        Raise this value if the global requests for your account are exceeding the DNSimple API rate limits.
      type: "int"
      min: 5000
      max: 60000
      default: 15000
      required: true

dnsimple:
  health_check:
    port: 1000
    interval: ${HEALTH_CHECK}
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
