.catalog:
  name: Zeppelin
  version: 0.1
  description: Web-based notebook that enables data-driven, interactive data analytics and collaborative documents with SQL, Scala and more.
  uuid: Zeppelin-0
  minimum_rancher_version: v0.46.0
  questions: 
    - variable: PORT
      default: 8080
      label: Public port
      required: true
